version: "3.9"
services:
  web:
    build: .
    ports:
      - "80:8000"
    env_file:
      - ./.env.prod
    depends_on:
      - db
  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db

  volumes: 
    postgres_data:

